spring:
  datasource:
    # url: jdbc:mysql://localhost:3306/gestionstockdb?createDatabaseIfNotExist=true&userSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    url: jdbc:mariadb://localhost:3306/gestionstockdb?createDatabaseIfNotExist=true&userSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: ""
    # driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: org.mariadb.jdbc.Driver
  ## specify DBMS
  jpa:
    #database: MYSQL
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: false

    # Hibernate DDL Auto (create, create-drop, update)
    hibernate:
      ddl-auto: update
    # properties:
      # hibernate:
        # dialect: org.hibernate.dialect.MySQLDialect

    # Configuration optionnelle pour Ã©liminer le WARN Open-In-View
    open-in-view: false

    properties:
      hibernate:
        session_factory:
          statement_inspector: chijouProjects.gestion_stock_api.interceptor.Interceptor

server:
  port: 8081
  servlet:
    context-path: /gestion-stock-api

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs



